set -g status-style "bg={{background}},fg={{foreground}}"
set -g status-left-style "bg={{color4}},fg={{background}},bold"
set -g status-right-style "bg={{background}},fg={{foreground}}"
set -g window-status-style "bg={{background}},fg={{color8}}"
set -g window-status-current-style "bg={{color4}},fg={{background}},bold"
set -g pane-border-style "fg={{color8}}"
set -g pane-active-border-style "fg={{color4}}"
set -g message-style "bg={{color4}},fg={{background}}"
set -g mode-style "bg={{color4}},fg={{background}}"
