# #######################################################################################
# AUTOSTART
# #######################################################################################

# Autostart necessary processes (like notifications daemons, status bars, etc.)

exec-once = waybar
exec-once = hyprpaper
exec-once = firefox
exec-once = hypridle
exec-once = swaync
exec-once = wl-paste --watch cliphist store
exec-once = systemctl --user start hyprpolkitagent
exec-once = systemctl --user start elephant
exec-once = walker --gapplication-service

#for libadwaita gtk4 apps you can use this command:
exec-once = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"   # for GTK4 apps

#for gtk3 apps you need to install adw-gtk3 theme (in arch linux sudo pacman -S adw-gtk-theme)
exec-once = gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3"   # for GTK3 apps

#for kde apps you need to install: sudo pacman -S qt5ct qt6ct kvantum kvantum breeze-icons
