# #######################################################################################
# MONITORS
# #######################################################################################

# See https://wiki.hypr.land/Configuring/Monitors/
# 4K OLED at 240Hz with 1.25x scaling and VRR enabled
monitor = DP-2, 3840x2160@240, 0x0, 1.25, vrr, 1
