# #######################################################################################
# WINDOW AND WORKSPACE RULES
# #######################################################################################

# Smart gaps
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0

windowrule {
    name = no-gaps-wtv1
    match:float = false
    match:workspace = w[tv1]
    border_size = 0
    rounding = 0
}

windowrule {
    name = no-gaps-f1
    match:float = false
    match:workspace = f[1]
    border_size = 0
    rounding = 0
}

windowrule {
    name = suppress-maximize-events
    match:class = .*
    suppress_event = maximize
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false
    no_focus = true
}

windowrule {
    name = move-hyprland-run
    match:class = hyprland-run
    move = 20 monitor_h-120
    float = yes
}

windowrule {
    name = float-pavucontrol
    match:class = ^pavucontrol$
    float = yes
}

windowrule {
    name = float-blueman
    match:class = ^blueman-manager$
    float = yes
}

windowrule {
    name = float-nm-connection-editor
    match:class = ^nm-connection-editor$
    float = yes
}

windowrule {
    name = float-qalculate
    match:class = ^qalculate-gtk$
    float = yes
}

windowrule {
    name = pip-rules
    match:title = ^Picture-in-Picture$
    float = yes
    pin = yes
}

windowrule {
    name = float-xdg-desktop-portal
    match:class = ^xdg-desktop-portal-gtk$
    float = yes
}
