# #######################################################################################
# LOOK AND FEEL
# #######################################################################################

source = ~/.cache/wallust/colors-hyprland.conf

# Refer to https://wiki.hypr.land/Configuring/Variables/

general {
    gaps_in = 2
    gaps_out = 5
    border_size = 2
    col.active_border = $color4 $color5 45deg
    col.inactive_border = $background
    resize_on_border = false
    allow_tearing = false
    layout = dwindle
}

decoration {
    rounding = 12
    rounding_power = 2

    # Change transparency of focused and unfocused windows
    active_opacity = 0.95
    inactive_opacity = 0.85
    dim_inactive = true
    dim_strength = 0.1

    shadow {
        enabled = true
        range = 15
        render_power = 4
        color = rgba(00000044)
    }

    blur {
        enabled = true
        size = 6
        passes = 3
        ignore_opacity = true
        new_optimizations = true
        vibrancy = 0.1696
    }
}

animations {
    enabled = yes

    # Awesome 2026 bouncy and expressive curves
    bezier = overshot, 0.05, 0.9, 0.1, 1.05
    bezier = smoothOut, 0.36, 0, 0.66, -0.56
    bezier = smoothIn, 0.25, 1, 0.5, 1

    animation = windows, 1, 5, overshot, slide
    animation = windowsOut, 1, 4, smoothOut, slide
    animation = windowsMove, 1, 4, default
    animation = border, 1, 10, default
    animation = borderangle, 1, 30, default, loop
    animation = fade, 1, 5, smoothIn
    animation = workspaces, 1, 6, default, slidefade 20%
}

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    new_status = master
}

misc {
    force_default_wallpaper = 0
    disable_hyprland_logo = true
    disable_splash_rendering = true
    mouse_move_enables_dpms = true
    key_press_enables_dpms = true
}
