# wallust configuration file

# How the image is parsed. Can be 'kmeans', 'fastkmeans', 'quantize' or 'mix'
backend = "kmeans"

# Color space used. Can be 'srgb', 'hsl', 'lch', 'lab', 'oklab' or 'oklch'
color_space = "oklab"

# Threshold for contrast.
threshold = 11

# The fallback if wallust fails
fallback_generator = "interpolate"

[[entry]]
template = "colors-hyprland.conf"
target = "~/.cache/wallust/colors-hyprland.conf"

[[entry]]
template = "colors-anyrun.css"
target = "~/.cache/wallust/colors-anyrun.css"

[[entry]]
template = "colors-waybar.css"
target = "~/.cache/wallust/colors-waybar.css"

[[entry]]
template = "colors-kitty.conf"
target = "~/.cache/wallust/colors-kitty.conf"

[[entry]]
template = "colors-ghostty.conf"
target = "~/.cache/wallust/colors-ghostty.conf"
