# #######################################################################################
# MAIN HYPRLAND CONFIG
# #######################################################################################

# This configuration has been modularized for easier maintenance and dynamic theming.
# Each specific section is sourced from the conf.d directory below.

source = ~/.config/hypr/conf.d/monitors.conf
source = ~/.config/hypr/conf.d/programs.conf
source = ~/.config/hypr/conf.d/autostart.conf
source = ~/.config/hypr/conf.d/env.conf
source = ~/.config/hypr/conf.d/ui.conf
source = ~/.config/hypr/conf.d/input.conf
source = ~/.config/hypr/conf.d/binds.conf
source = ~/.config/hypr/conf.d/rules.conf
